### ISSUE TITLE
Path Format incorrect under Windows + search-history.html missing

### ISSUE THREAD

**Issue by kilitr** [A3M4/YouTube-Report#22]
Okay, so I've run across multiple Issues..

The First Major one is, that i wanted to run it under Windows, but the Path's were incorrect - this one was quickly resolved by using Pythons builtin pathlib (https://github.com/kilitr/YouTube-Report/commit/5d6b2cee5ae405246dd2b95f7209034296b51258)

However, then the next problems occured for me.

1. My filestructure is in my native language German - so the Script is still not able to run. ~~#17~~ #5
2. I am missing the file "history/search-history.html" probably because I disabled this in my Google account...

For 2: Is there a way of generating the report without the data from this file?

**Comment by prateek754** [comment]
I have the same issue.

**Comment by prateek754** [comment]
I got a workaround. Just enable the search history for sometime. Do the takeout. Turn off search history.

**Comment by drayavannie** [comment]
#22
