### ISSUE TITLE
Support of parsing date format in dd MMM YYYY needed

### ISSUE THREAD

**Issue by cjcm567** [A3M4/YouTube-Report#26]
Hi there

I believe the RegEX used in Parse.py 
`(?:[A-Za-z]{3}\s\d{1,2}\,\s[0-9]{4}\,|\d{1,2}\s.{9})\s\d?\d:\d\d:\d\d\s(?:PM\s|AM\s)?[A-Z]{3,4}`
would only parse datetime format in MMM dd yyyy, which is the American way? 

Support of parsing date format in dd MMM YYYY is needed for ppl living in Britain, Aus and NZ. We have the date format in dd MMM YYYY (e.g. 25 Dec 2019).

Cheers! And Marry Xmas!

**Comment by JHJohny** [comment]
Hi,
I changed my language to English UK (in google account) so my format is - `15 Dec 2019, 15:38:06 UTC`
I report works fine.
Could you please try again or update repository (maybe meanwhile author added support for different date format)
