### ISSUE TITLE
Add error handling for missing/empty data files

### ISSUE THREAD

**Issue by arpreq** [A3M4/YouTube-Report#3]
Unhandled exceptions get thrown in `parse.py` when a data file can't be found (on lines 19-21) and when a data file is empty (including, but not limited to, lines 78 & 88).

My Youtube data didn't have the `my-comments` file, or the `likes` playlist.

**Comment by A3M4** [comment]
I fixed it with ee75532. Could you check if it works for you now?

**Comment by arpreq** [comment]
Works great for my specific case. Thanks!
